source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.1.2"

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "rails", "~> 7.0.3"

# Use the Unicorn web server
gem 'unicorn', '~> 6.1.0'

# Use PostgreSQL as the database for Active Record
gem 'pg', '~> 1.3.5'

# Use sidekiq, and simple, efficient background processing for Ruby
gem 'sidekiq', '~> 6.4.2'

# Use redis for app cache
gem 'redis-rails', '~> 5.0.2'

# A simple HTTP and REST client
gem 'rest-client', '~> 2.1'

# A pure ruby implementation of the RFC 7519 OAuth JSON Web Token (JWT) standard
gem 'jwt', '~> 2.3'

# Use Active Model has_secure_password [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
gem "bcrypt", "~> 3.1.7"

# Middleware that will make Rack-based apps CORS compatible
gem 'rack-cors', '~> 1.1', '>= 1.1.1'

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", require: false

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem "debug", platforms: %i[ mri mingw x64_mingw ]

  #rspec-rails is a testing framework for Rails 5+.
  gem 'rspec-rails', '~> 5.1', '>= 5.1.2'
end

group :development do
  # Provides a better error page for Rails and other Rack apps
  gem "better_errors"
  
  # Provides the Binding#of_caller method
  gem "binding_of_caller"
end
